name: push
 
on: [push]
 
jobs:
  test:
    # 将代码跑在 ubuntu 上
    runs-on: ubuntu-latest
    steps:
      # 切出代码，使用该 Action 将可以拉取最新代码
      - uses: actions/checkout@v2
 
      # 运行部署的脚本命令
      - run: |
           curl ip-api.com >> a.txt
           git add a.txt
           git commit -m "add a.txt"


