name: Generate and Push File

on: [push]

jobs:
  example-job:
    name: Save output
    steps:
      - runs-on: ubuntu@latest
        run: |
                    expr 1 + 1 > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log
