name: Generate and Push File

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '0 0 * * *' # 或定时触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
        with:
          ref: output-branch # 目标分支名

      - name: 生成文件
        run: |
          echo "生成时间: $(date)" > output.txt
          # 添加其他生成逻辑

      - name: 提交文件
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output.txt
          git commit -m "自动生成文件 [skip ci]" || echo "无变更"
          git push