name: Generate and Push File

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 生成文件
        run: |
          echo "生成时间: $(date)" > output.txt
          # 添加其他生成逻辑

      - name: 提交文件
        run: |
          echo "444">>output
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: output
